[package]
name = "cureety"
version = "0.1.0"
edition = "2021"

[alias]
b = "build"
c = "check"
d = "doc"
t = "test"
r = "run"
rm = "remove"
docker_up = ["docker", "compose", "up", "-d"]

[dependencies]
actix-web = "4.8.0"
dotenv = "0.15.0"
